### PR TITLE
Fixed non draco export

### LINKED ISSUE #2: Fix none-Draco code path
There is a bunch of disabled code here: https://github.com/Doerge/glTF-Bin/blob/a1da0b3a1e816646b97836be8e751f397e36daa2/glTF-BinExporter/glTF/GlTFRootModel.cs#L519 that previously allowed exports without Draco compression. It was disabled to speed up development of features such as textures.
It should be enabled again, and all the primitive attribute handling such as normals, texcoords etc. should be updated.

### PR DESCRIPTION
**Pull request by jrz371**
Resolves #2 

It might be worth taking a close look at this one to see if I did anything crazy.

I had the save file dialog created based on whether its the binary (.glb) or text (.gtlf) and added back the other Rhino.Gets for the export options.

I also think you forgot to add the json ignore attribute over the buffers raw bytes field.

In the SerializeToGLB I made it so the buffers are cleared before you add the packed buffer. Otherwise all the BufferViews look at whatever the first buffer was and not the packed buffer since it's at the end.

### CODE REVIEW

**Comment by jrz371** [comment]
Any updates on this?

**Comment by Doerge** [comment]
Yes, I'll carve out some time to test it later today, so we can include it before beginning work on the Loader!

**Comment by jrz371** [comment]
I've got a fix for #12 built on top of this, I can push the commit to this pull as well if you want?

**Comment by Doerge** [comment]
Sorry, just saw your comment now. Let's keep it separate, but I'll keep the ball rolling in the evenings to get stuff merged.

Please review my additions in the other PR #20

**Comment by jrz371** [comment]
Hi,

I think you should push the commit to this PR so it's all bundled with the rest of this conversation. I've allowed edits by maintainers so you should be able to do it.

I was silly forgetting the Z -> Y conversion. I logged #21 since the Z up -> Y up conversion needs sorted a bit better, but for now it's not getting in the way.

It doesn't look like you used the texCoords min and max down in the accessor. I might be wrong, but I don't think we need to calculate those or the normal min and maxes either? I'll need to double check.

File: glTF-BinExporter/glTF/GlTFUtils.cs [hunk 1]
```diff
@@ -157,5 +157,12 @@ public static void ExportBinary(MemoryStream outStream, IEnumerable<RhinoObject>
 
             outStream.Flush();
         }
+
+        public static int AddAndReturnIndex<T>(this List<T> list, T item)
```
Comment (Doerge) [inline glTF-BinExporter/glTF/GlTFUtils.cs:161]: 💎 🎉  Nice! These kind of helper functions are super welcome to declutter everything a bit.

File: glTF-BinExporter/GlTFExporterCommand.cs [hunk 2]
```diff
@@ -89,8 +86,32 @@ protected override Result RunCommand(Rhino.RhinoDoc doc, RunMode mode)
                 return Result.Success;
             } catch (Exception e) {
                 RhinoApp.WriteLine("ERROR: Failed exporting selected geometry to file.");
+                System.Diagnostics.Debug.WriteLine(e.Message);
                 return Result.Failure;
             }
         }
+
+        private SaveFileDialog GetSaveFileDialog(bool binaryExport)
```
Comment (Doerge) [inline glTF-BinExporter/GlTFExporterCommand.cs:94]: 🎉  Sweet!

File: glTF-BinExporter/glTF/GlBuffer.cs [hunk 3]
```diff
@@ -29,6 +29,7 @@ public class Buffer
         public bool IsGLBinaryMode;
 
         // dump to byte[] with ".flatten" + .ToArray();
+        [JsonIgnore]
```
Comment (Doerge) [inline glTF-BinExporter/glTF/GlBuffer.cs:32]: Yikes. Thanks!

File: glTF-BinExporter/glTF/GlBuffer.cs [hunk 4]
```diff
@@ -75,6 +76,22 @@ public void Add(Point3d point)
...
 
+        public void Add(Vector3d point)
+        {
+            // Switch GL coords for Y<=>Z
+            float[] coords = new float[] { (float)point.X, (float)point.Z, -(float)point.Y };
+            Add(coords);
+            PrimitiveCount += 1;
+        }
+
+        public void Add(Point2f point)
```
Comment (Doerge) [inline glTF-BinExporter/glTF/GlBuffer.cs:87]: @jrz371 I went with `Point2f` because that was the type of the texcoord. But honestly don't know if it should be `Point2d` instead, and didn't lookup the difference. Any opinion?

File: glTF-BinExporter/glTF/GlTFRootModel.cs [hunk 5]
```diff
@@ -145,6 +146,9 @@ public void SerializeToGLB(in MemoryStream memoryStream)
                     bv.byteOffset = bv.bufferRef.binaryOffset;
                 }
 
+                //Have to get rid of the other buffers so only the new buffer
+                //all the data was dumped into remains
+                buffers.Clear();
```
Comment (Doerge) [inline glTF-BinExporter/glTF/GlTFRootModel.cs:151]: Man... how did that even work before? 👍  Thanks!

While reviewing this I realize I may have misunderstood the spec initially: I now think it is valid to create multiple binary buffers, instead of mashing everything into one and using views to discern the data blobs. Not sure what the implications are of that yet. The validator fails with:
```
           {
                "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
                "message": "Accessor's total byteOffset 397965 isn't a multiple of componentType length 4.",
                "severity": 0,
                "pointer": "/accessors/0"
            },
```
Maybe that's a side effect of this weird choice. Will create a separate ticket for that though.

File: glTF-BinExporter/glTF/GlTFRootModel.cs [hunk 6]
```diff
@@ -518,90 +522,174 @@ private TextureEmissive AddTextureEmissive(string texturePath)
...
+                    max = new float[] { (float)normalsMax.X, (float)normalsMax.Y, (float)normalsMax.Z }
+                };
+                int normalsAccessorIdx = accessors.AddAndReturnIndex(normalsAccessor);
+
+                AccessorVec2 texCoordsAccessor = new AccessorVec2()
+                {
+                    bufferView = texCoordsBufferViewIdx,
+                    count = rhinoMesh.TextureCoordinates.Count,
+                    min = new float[] { (float)texCoordsMin.X, (float)texCoordsMin.Y },
+                    max = new float[] { (float)texCoordsMax.X, (float)texCoordsMax.Y }
```
Comment (Doerge) [inline glTF-BinExporter/glTF/GlTFRootModel.cs:668]: Fixed texcoords min/max here. Thanks!

**Review by Doerge — COMMENTED** [review]
> I've allowed edits by maintainers so you should be able to do it.

I didn't know that was possible! 🤯 

Great that you created #21 ! Agreed it should be an option.

Ah. I thought validators might fail us, if we didn't keep proper track of min/max. I plugged them in for now. They don't hurt other than taking a bit of extra processing.
Texcoords might also have use cases outside [0, 1] if the user is super creative with the UV layout and wrapping modes. Not sure if Normals are guaranteed to be normalized by the gltf spec, but that would be a reasonable assumption 😄

File: glTF-BinExporter/GlTFExporterCommand.cs (hunk 2 above)
Comment (jrz371) [reply glTF-BinExporter/GlTFExporterCommand.cs:94]: I've been thinking this probably needs cleaned up a bit more. We can infer the binary or text from the extension. We can add both options to the SaveFileDialog filter and go from there.

File: glTF-BinExporter/glTF/GlBuffer.cs (hunk 4 above)
Comment (jrz371) [reply glTF-BinExporter/glTF/GlBuffer.cs:87]: Point2f is single precision and Point2d is double. glTF only supports single precision so there's nothing to worry about here.

File: glTF-BinExporter/glTF/GlTFUtils.cs (hunk 1 above)
Comment (jrz371) [reply glTF-BinExporter/glTF/GlTFUtils.cs:161]: We can cleanup the old ones as we go. It'll probably have to be after we switch to the glTF lib backend.

File: glTF-BinExporter/glTF/GlTFRootModel.cs (hunk 5 above)
Comment (jrz371) [reply glTF-BinExporter/glTF/GlTFRootModel.cs:151]: Yes, I think this changed. While we probably can cram multiple things into a single buffer it's unnecessarily complicated and makes the code and final output file confusing. The validator error makes sense to me since we're probably mixing floats/bytes/integers all in one buffer and just fiddling with offsets. It's not super imperative though so we'll get to #22 when either of us has a chance.
